/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config = 
{
  address: '0.0.0.0',
  ipWhitelist: [
    '127.0.0.1',
    '::ffff:127.0.0.1',
    '::1',
    '::ffff:192.168.0.1/120',
    '192.168.0.1/24'
  ],
  units: 'imperial',
  modules: [
    {
      module: 'alert',
      config: {}
    },
    {
      module: 'updatenotification',
      position: 'top_bar',
      config: {}
    },
    {
      module: 'clock',
      position: 'top_right',
      config: {},
      header: ''
    },
    {
      module: 'calendar',
      header: 'US Holidays',
      position: 'top_right',
      config: {
        calendars: [
          {
            symbol: 'calendar-check',
            url: 'webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics'
          }
        ]
      }
    },
    {
      module: 'currentweather',
      position: 'top_left',
      config: {
        location: 'Arlington, TX',
        locationID: '4671240',
        appid: '#####'
      }
    },
    {
      module: 'weatherforecast',
      position: 'top_left',
      config: {
        location: 'Arlington, TX',
        locationID: '4671240',
        appid: '#####'
      }
    },
    {
      module: 'MMM-RemoteCompliments',
      header: 'Notes',
      position: 'bottom_left',
      config: {}
    },
    {
      module: 'newsfeed',
      position: 'bottom_bar',
      config: {
        feeds: [
          {
            title: 'NBC 5 Dallas-Fort Worth',
            url: 'https://www.nbcdfw.com/?rss=y'
          }
        ]
      }
    },
    {
      module: 'MMM-Scrobbler',
      position: 'top_left',
      config: {
        username: '#####',
        apikey: '#####'
      },
      header: 'Music Listening...'
    },
    {
      module: 'MMM-Remote-Control',
      position: 'lower_third',
      config: {
        showModuleApiMenu: false,
        secureEndpoints: true
      }
    },
    {
      module: 'MMM-MyCommute',
      position: 'bottom_right',
      header: 'Traffic',
      config: {
        apikey: '#####',
        origin: 'address',
        destinations: [
          {
            destination: 'address',
            label: 'WORK',
            mode: 'driving',
            color: '#82E5AA',
            avoid: 'tolls',
            alternatives: true
          },
          {
            destination: 'address',
            label: 'SCHOOL',
            mode: 'driving',
            color: '#ffff00',
            avoid: 'tolls',
            alternatives: true
          }
        ],
        pollFrequency: 800000
      }
    },
    {
      module: 'calendar',
      position: 'top_right',
      header: '',
      config: {
        maximumNumberOfDays: 10,
        maximumEntries: 7,
        calendars: [
          {
            url: 'http://localhost:8080/modules/calendars/home.ics',
            symbol: 'calendar',
            color: '#82E5AA'
          }
        ],
        fetchInterval: 150000,
        animationSpeed: 30000
      }
    },
    {
      module: 'MMM-iFrame-Ping',
      position: 'fullscreen',
      config: {
        url: 'https://www.youtube.com/embed/###&autoplay=1&loop=1&modestbranding=1&iv_load_policy=3',
        height: '800px',
        autoRefresh: false,
        updateInterval: 2,
        displayLastUpdate: false
      }
    }
  ],
  useHttps: false,
  httpsPrivateKey: '',
  httpsCertificate: '',
  logLevel: [
    'INFO',
    'LOG',
    'WARN',
    'ERROR'
  ]
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
